# -*- coding: utf-8 -*-
{
    "name": "Shopify Connector",
    'author': 'Reliution',
    'website': 'https://www.reliution.com/',
    'license': 'AGPL-3',
    'version': '17.0.0.1',
    'sequence': 0,
    "depends": ['base', 'sale_stock', 'sale_management', 'rcs_process_logs', 'product', 'stock_delivery'],
    "data": [
        'security/shopify_connector_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'views/shopify_dashboard_view.xml',
        'views/shopify_queue_manage_line_view.xml',
        'views/shopify_queue_manage_view.xml',
        'views/shopify_payment_gateway_views.xml',
        'views/shopify_sale_order_process_configuration_views.xml',
        'views/sale_order_automation_views.xml',
        'views/shopify_product_template_view.xml',
        'views/shopify_product_product_view.xml',
        'views/shopify_menu.xml',
        'views/shopify_connector_view.xml',
        'views/res_partner_view.xml',
        'views/sales_order_view.xml',
        'wizard/shopify_operations_wizard_view.xml',
    ],
    'images': ['static/description/banner.gif'],
    'assets': {
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    "category": "Sales/Sales",
}
